print("                       MINIMART")
print("======================================================")
cola=     int(input("cola         @ 10 bath : want to buy : "))
greentea= int(input("green tea    @ 12 bath : want to buy : "))
milk=     int(input("milk         @ 15 bath : want to buy : "))
energy=   int(input("energy drink @ 20 bath : want to buy : "))
fruit=    int(input("fruit juice  @ 22 bath : want to buy : "))
print("======================================================")
print("Cola summerry            = ",cola)
print("Green tea summerry       = ",greentea)
print("Milk summerry            = ",milk)
print("Energy Drink summerry    = ",energy)
print("Fruit summerry           = ",fruit)
print("======================================================")
print("Cola price summerry      = ",10*cola) 
print("Green tea price summerry = ",12*greentea)
print("Milk price summerry      = ",15*milk)
print("Enery price summerry     = ",20*energy)
print("Fruit price summerry     = ",22*fruit)
print("======================================================")
lastmoney = (10*cola) + (12*greentea) + (15*milk) + (20*energy) + (22*fruit)
print("Sale summerry = ",lastmoney)
vat = (lastmoney*7)/100
print("Vat : ",vat)
taxsummerry = vat + lastmoney
print("LAST PRICE : ",taxsummerry)
#product = cola + greentea + milk + energy + fruit
#print("product summerry = ",product)
print("======================================================")