num1 = int(input("Enter num 1 : "))
num2 = int(input("Enter num 2 : "))
num3 = int(input("Enter num 3 : "))
print("Result of ",num1 ,"+" ,num2 ,"+" ,num3, "= ",num1+num2+num3)
print("2 X Num1 =",num1*2)